language: go
go:
  - "1.x"
  - "1.9.x"
  - "1.10.x"
  - master
sudo: false
install:
  - go get -u github.com/kamisari/go-todogotcha/gotcha
script:
  - cd gotcha && go test -v -race -cover
  - gotcha gotcha/main.go
